<?php
/**
 * Created by PhpStorm.
 * User: lex
 * Date: 23.12.2015
 * Time: 19:47
 */

namespace Course\Form;


use Zend\Form\Form;
use Zend\ServiceManager\ServiceLocatorAwareInterface;
use Zend\ServiceManager\ServiceLocatorAwareTrait;

class Courses extends Form implements ServiceLocatorAwareInterface
{
    use ServiceLocatorAwareTrait;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->add(array(
            'name' => 'cost',
            'type' => 'Text',
            'options' => array(
                'label' => 'Цена в USD',
            )
        ));

        $this->add(array(
            'name' => 'currency',
            'type' => 'DoctrineModule\Form\Element\ObjectSelect',
            'options' => array(
                'object_manager' => $this->getServiceLocator()->getServiceLocator()->get('doctrine-document'),
                'target_class' => 'Course\Document\Courses',
                'label' => 'Валюта'
            )
        ));

        $this->add(array(
            'name' => 'countThread',
            'type' => 'Select',
            'options' => array(
                'label' => 'Количество потоков',
                'value_options' => array(
                    '1',
                    '5',
                    '10',
                    '50',
                    '100',
                    '500',
                    '1000'
                )
            ),
        ));

        $this->add(array(
            'name' => 'start',
            'type' => 'Button',
            'options' => array(
                'label' => 'Старт'
            ),
            'attributes' => array(
                'class' => 'btn start'
            )
        ));
    }
}